[package]
name = "gru-opengl"
version = "0.1.0"
authors = ["Jannik Fehre"]
edition = "2018"

[dependencies]
glow = "0.9.0"

# desktop
[target.'cfg(not(any(target_arch = "wasm32", target_os = "android")))'.dependencies]
winit = { version = "0.24.0", features = [] }
raw-gl-context = "0.1.2"

# web
[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.24.0", features = ["web-sys"] }
#js-sys = "0.3.50"
wasm-bindgen = "0.2.73"
web-sys = { version = "0.3.4", features = ['Document', 'Element', 'HtmlCanvasElement', 'WebGlBuffer', 'WebGlRenderingContext', 'WebGlProgram', 'WebGlShader', 'Window'] }

# android
[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.24.0", features = [] }
raw-window-handle = "0.3.3"
ndk-glue = "0.2.1"
khronos-egl = { version = "4.1.0", features = ["dynamic"] }
libloading = "0.7.0"
#log = "0.4.14"
